<%@page import="org.json.JSONObject"%>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.HashMap"%>
<%@page import="java.util.Map"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%
	Map<String, String> fieldList = new HashMap<>();		
	fieldList.put("email", " {\n\"type\": \"email\",\n\"id\": \"emailAddress\",\n\"name\": \"emailAddress\",\n\"label\": \"Enter Email\",\n\"classes\":\"form-control\",\n\"placeholder\": \"Enter your email address\",\n\"suggestion\": \"\",\n\"config\": {\n\"disabled\": false,\n\"readOnly\": false,\n\"checked\": false,\n\"hidden\": false\n},\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"email\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	fieldList.put("firstName"," {\n\"type\": \"text\",\n\"id\": \"firstName\",\n\"name\": \"firstName\",\n\"label\": \"First Name\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your first name\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");
	fieldList.put("middleName"," {\n\"type\": \"text\",\n\"id\": \"middleName\",\n\"name\": \"middleName\",\n\"label\": \"Middle Name\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your middle name\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");
	fieldList.put("lastName"," {\n\"type\": \"text\",\n\"id\": \"lastName\",\n\"name\": \"lastName\",\n\"label\": \"Last Name\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter Last Last\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("password"," {\n\"type\": \"password\",\n \"id\": \"password_\",\n\"name\": \"password_\",\n\"label\": \"Enter Password\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your password\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"password\",\n            \"errorMessage\": \" Please Enter the valid data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"6\",\n    \"pattern\":\"18\",\n          }\n        }");	
	 fieldList.put("submitAction"," {\n\"type\": \"submit\",\n \"id\": \"password_\",\n\"name\": \"password_\",\n\"label\": \"Enter Password\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your password\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"password\",\n            \"errorMessage\": \" Please Enter the valid data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"6\",\n    \"pattern\":\"18\",\n          }\n        }");	
	fieldList.put("editAction"," {\n\"type\": \"edit\",\n \"id\": \"password_\",\n\"name\": \"password_\",\n\"label\": \"Enter Password\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your password\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"password\",\n            \"errorMessage\": \" Please Enter the valid data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"6\",\n    \"pattern\":\"18\",\n          }\n        }");	
	fieldList.put("cancelAction"," {\n\"type\": \"cancel\",\n \"id\": \"password_\",\n\"name\": \"password_\",\n\"label\": \"Enter Password\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your password\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"password\",\n            \"errorMessage\": \" Please Enter the valid data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"6\",\n    \"pattern\":\"18\",\n          }\n        }");	 
	request.setAttribute("formDefinition", fieldList);
%>
	<%@ include file="form_render.jsp" %>
	
